Make constructor public so that it can be called
At least with my version of Java, if that constructor is not explicitly defined as public, it is not possible to create a MCSLock from the Benchmark.java in the upper directory level. This triggers an error like:
```
error: MCSLock() is not public in MCSLock; cannot be accessed from outside package
```
Signed-off-by: Carlos Bilbao <bilbao@vt.edu>